version: '3.7'

services:
  web:
    build: 
      context: ./tweet_analyzer
      dockerfile: Dockerfile.prod
    command: gunicorn tweet_analyzer.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/tweet_analyzer/web/staticfiles
      - media_volume:/home/tweet_analyzer/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./env_prod.env

  nginx-proxy:
    container_name: nginx-proxy
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/tweet_analyzer/web/staticfiles
      - media_volume:/home/tweet_analyzer/web/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./env_prod_proxy-companion.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
