version: '3.7'

services:
  web:
    build: ./tweet_analyzer
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tweet_analyzer/:/usr/src/tweet_analyzer/
    ports:
      - 8000:8000
    env_file:
      - ./env_dev.env