# Generated by Django 3.1.1 on 2020-09-30 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1024)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('query_time', models.DateTimeField(auto_now_add=True)),
                ('twitter_response_status', models.CharField(max_length=3)),
                ('query_url', models.CharField(max_length=1500)),
                ('count', models.IntegerField(default=0)),
                ('data_count', models.IntegerField(default=0)),
                ('researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researcher', to='researcher.researcher')),
            ],
        ),
    ]
