# Generated by Django 3.1.1 on 2020-10-01 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0007_auto_20201001_1208'),
        ('search', '0003_auto_20201001_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='researcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search', to='researcher.researcher'),
        ),
    ]
