# Generated by Django 3.1.1 on 2020-10-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20201001_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='query',
            field=models.CharField(default='', max_length=1024, null=True),
        ),
    ]
