# Generated by Django 3.1.1 on 2020-09-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0002_auto_20200930_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='time_zone',
            field=models.CharField(default='America/Chicago', max_length=100),
        ),
    ]
