# Generated by Django 3.1.1 on 2020-10-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0006_researcher_request_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcher',
            old_name='request_limit',
            new_name='request_limit_30day',
        ),
        migrations.AddField(
            model_name='researcher',
            name='request_limit_fullarchive',
            field=models.IntegerField(default=0),
        ),
    ]
